#1. total revenue generated by female vs male customers
select gender, sum(purchase_amount) as revenue
from customer
group by gender

#2. which customers used a discount but still spent more than avg purchase amount
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer)

#3. top 5 products witht the highest avg review rating
select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by "Average Product Rating" desc
limit 5

#4. compare avg purchase amts between stanford and express shipping
select shipping_type,
round(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type

#5. do subscribed customers spend more? compare avg spend and total revenue between subscribed and non-subscribed customers
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc

#6. which 5 products have the highest percentage of purchases with discs applied    
select item_purchased,
round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/ count(*), 2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5

#7. segement customers into New, Returning, and Loyal based on their 
--total number of prev purchases and show the count of each segment
with customer_type as (
select customer_id, previous_purchases,
case 
when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 5 then 'Returning'
else 'Loyal'
end as customer_segment
from customer
)
select customer_segment, count(*) as "No. of customers"
from customer_type
group by customer_segment

#8. what are the top 3 most purchased products within each country? (advanced query using window functions)
with item_counts as (
    SELECT category, item_purchased, 
    COUNT(*) AS total_orders,
    row_number() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    from customer
    group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3

#9. are customers who are repeat buyers (> 5 purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

#10. revenue contribution of each age group?
select age_group, 
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc

